version: '3.4'
services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - '4001:80'
    networks:
      - xo-game
    restart: on-failure

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - redis
    ports:
      - '4000:4000'

    networks:
      - xo-game
    restart: on-failure

  db:
    image: mongo
    volumes:
      - mongodbData:/data/db
    command: mongod --port 27018
    ports:
      - '27018:27018'
    networks:
      - xo-game

  redis:
    image: redis
    ports:
      - 6380:6380
    command: --port 6380
    volumes:
      - redisdata:/data
    networks:
      - xo-game

volumes:
  mongodbData:
    driver: local

  redisdata:
    driver: local
networks:
  xo-game:
    driver: bridge
